##SPRING CONFIGURATIONS##
server:
  port: 8080
spring:
  application:
    name: retries-dlq-strategy
  devtools:
    add-properties: false
  rabbitmq:
    host: 192.168.1.1
    port: 5672
    username: guest
    password: guest

app:
  async:
    withDLQRetry: true
    retryDelay: 5000
    maxRetries: 3